### Register new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Joko",
  "username": "joko",
  "password": "joko"
}

### Login user
POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "username": "joko",
  "password": "joko"
}

### Get user profile
GET http://localhost:3000/api/users/_current
Accept: application/json
Authorization: {{token}}

### Logout user
DELETE http://localhost:3000/api/users
Accept: application/json
Authorization: {{token}}

### Update user
PATCH http://localhost:3000/api/users/_current
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Joko Morro"
}

### Create contact
POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "nik": "3200000000000001",
  "full_name": "Joko Morro",
  "legal_name": "Joko Morro",
  "birth_place": "Jakarta",
  "birth_date": "1990-01-01",
  "salary": 7500000,
  "ktp_photo": "https://example.com/ktp-joko.jpg",
  "selfie_photo": "https://example.com/selfie-joko.jpg"
}

### Get detail contact
GET http://localhost:3000/api/contacts/{{contactId}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

### Search contacts
GET http://localhost:3000/api/contacts?size=10&page=1&full_name=jo&legal_name=jo
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

### update contact
PUT http://localhost:3000/api/contacts/{{contactId}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "nik": "3200000000000002",
  "full_name": "Budi Nugraha",
  "legal_name": "Budi Nugraha",
  "birth_place": "Bandung",
  "birth_date": "1992-02-02",
  "salary": 8200000,
  "ktp_photo": "https://example.com/ktp-budi.jpg",
  "selfie_photo": "https://example.com/selfie-budi.jpg"
}

### delete contact
DELETE http://localhost:3000/api/contacts/{{contactId}}
Accept: application/json
Authorization: {{token}}

### get all addresses
GET http://localhost:3000/api/contacts/{{contactId}}/addresses
Accept: application/json
Authorization: {{token}}


### create new addresses
POST http://localhost:3000/api/contacts/{{contactId}}/addresses
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "street": "Jl. Jalan",
  "city": "Jakarta",
  "province": "DKI Jakarta",
  "country": "Indonesia",
  "postal_code": "12345"
}

### get address detail
GET http://localhost:3000/api/contacts/{{contactId}}/addresses/{{addressId}}
Accept: application/json
Authorization: {{token}}

### update address
PUT http://localhost:3000/api/contacts/{{contactId}}/addresses/{{addressId}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "street": "Jl. Sudah Jadi",
  "city": "Jakarta",
  "province": "DKI Jakarta",
  "country": "Indonesia",
  "postal_code": "12345"
}

### delete address
DELETE http://localhost:3000/api/contacts/{{contactId}}/addresses/{{addressId}}
Accept: application/json
Authorization: {{token}}
